import sarahImage from "../assets/userImages/photo-1438761681033-6461ffad8d80.jpeg";
import mikeImage from "../assets/userImages/photo-1507003211169-0a1dd7228f2d.jpeg";
import alexImage from "../assets/userImages/photo-1531251445707-1f000e1e87d0.jpeg";
import emmaImage from "../assets/userImages/photo-1546967191-fdfb13ed6b1e.jpeg";
import davidImage from "../assets/userImages/photo-1552058544-f2b08422138a.jpeg";
import lisaImage from "../assets/userImages/photo-1549351236-caca0f174515.jpeg";

export interface ChatBubbleData {
  id: number;
  user: {
    name: string;
    image: string;
    alt: string;
  };
  message: string;
  time: string;
  className: string;
  animationDelay: string;
  zIndex: number;
  isTyping?: boolean;
}

export const mockChatBubbles: ChatBubbleData[] = [
  {
    id: 1,
    user: { name: "Lisa Zhang", image: lisaImage, alt: "Lisa" },
    message: "Blockchain is the future",
    time: "just now",
    className: "bubble-1",
    animationDelay: "0s",
    zIndex: 7,
  },
  {
    id: 2,
    user: { name: "Sarah Chen", image: sarahImage, alt: "Sarah" },
    message: "Great meeting you!",
    time: "30s ago",
    className: "bubble-2",
    animationDelay: "0.3s",
    zIndex: 6,
  },
  {
    id: 3,
    user: { name: "Mike Rodriguez", image: mikeImage, alt: "Mike" },
    message: "Tether has been shooting up",
    time: "2m ago",
    className: "bubble-3",
    animationDelay: "0.6s",
    zIndex: 5,
  },
  {
    id: 4,
    user: { name: "Alex Kim", image: alexImage, alt: "Alex" },
    message: "Thanks for the intro to the Algorand team!",
    time: "5m ago",
    className: "bubble-4",
    animationDelay: "0.9s",
    zIndex: 4,
  },
  {
    id: 5,
    user: { name: "Emma Watson", image: emmaImage, alt: "Emma" },
    message: "These messages were generated by Claude!",
    time: "8m ago",
    className: "bubble-5",
    animationDelay: "1.2s",
    zIndex: 3,
  },
  {
    id: 6,
    user: { name: "David Park", image: davidImage, alt: "David" },
    message: "Are we even real?!",
    time: "12m ago",
    className: "bubble-6",
    animationDelay: "1.5s",
    zIndex: 2,
  },
  {
    id: 7,
    user: { name: "Lisa Zhang", image: lisaImage, alt: "Lisa" },
    message: "",
    time: "",
    className: "bubble-7",
    animationDelay: "1.8s",
    zIndex: 1,
    isTyping: true,
  },
];